### ISSUE TITLE
Add API for .children()

### ISSUE THREAD

**Issue by abuuzayr** [franciscop/react-test#1]
Hey @franciscop thank you for sharing this library! 

I'm adding issues to indicate that I am working on an API, just in case you or someone else also wants to also work on them. 

Hope that's ok, do let me know if you feel otherwise.

**Comment by franciscop** [comment]
Hi @abuuzayr, please feel free to do it! Also add some tests please. While it's up to you, you can use [jQuery's .children() docs](https://api.jquery.com/children/) or [Umbrella's .children() docs](https://umbrellajs.com/documentation#children) as inspiration.

**Comment by abuuzayr** [comment]
Roger that, I'll add tests as you have for the other APIs. 

I'll reach out here if I come across any blockers. Thank you for being so helpful!
