### ISSUE TITLE
Add API for .siblings() 

### ISSUE THREAD

**Issue by abuuzayr** [franciscop/react-test#10]
Hi 👋 , this is an issue for those who want to start contributing to Open Source. Please make sure to [read the Contributing.md guide](https://github.com/franciscop/react-test/blob/master/Contributing.md) to install this library for dev. Then you can solve this issue, ask questions around and submit a Pull Request when you are ready! We'll review it and give tips.

***

Get all of the nodes within the same level, except itself:

```js
const $list = $(
  <ul>
    <li>A</li>
    <li className="active">B</li>
    <li>C</li>
  </ul>
);

console.log($list.find('.active').siblings().html());
// <li>A</li><li>C</li>
```

### Acceptance criteria

- [ ] API for testing with `.siblings()` method
- [ ] Basic tests for `.siblings()`

### Nice to have but not required

- [ ] Documentation
- [ ] Tests for edge cases

### References

- [React Test's `.find()`](https://github.com/franciscop/react-test/tree/master/src/methods/find) as an example of a well-defined method.
- [Umbrella's `.siblings()`](https://umbrellajs.com/documentation#siblings) as an example of documentation for a similar method.
- [jQuery's `.siblings()`](https://api.jquery.com/siblings/) the original one.

**Comment by franciscop** [comment]
Please hold on building this, see https://github.com/franciscop/react-test/issues/32
