### ISSUE TITLE
Add jest-dom

### ISSUE THREAD

**Issue by franciscop** [franciscop/react-test#15]
Or at least consider it. Currently, if added blindly it adds 45kb to the library so I don't think it's a good idea.

| Now      | + jest-dom   |
|--------|------------------|
| 937 bytes  | 45543 bytes |

[Bundlephobia seems to confirm it](https://bundlephobia.com/result?p=@testing-library/jest-dom@5.1.1).

**Comment by abuuzayr** [comment]
And you reduced it to ~34.2KB with your merged PR 😄 

But that aside, you are right. Adding `jest-dom` will add some bloat, which may be unnecessary though maybe they're nice for dev experience. 

To write these custom matchers:

```
toBeDisabled
toBeEnabled
toBeEmpty
toBeInTheDocument
toBeInvalid
toBeRequired
toBeValid
toBeVisible
toContainElement
toContainHTML
toHaveAttribute
toHaveClass
toHaveFocus
toHaveFormValues
toHaveStyle
toHaveTextContent
toHaveValue
toBeChecked
```

Do you think what we need to roll our own are already in `react-test` deps?

**Comment by franciscop** [comment]
I am unsure about that. It's quite a bit of extra work, I added [toHaveClass](https://github.com/franciscop/react-test/blob/master/src/jest/toHaveClass.js) to see how it works and while it does work very nicely, those are a lot of methods.

But we cannot use `jest-dom` straight away since react-test doesn't return a plain HTMLElement, so a bit of workaround would be needed:

```js
// If we own it
const counter = $(<Counter />);
expect(counter).toHaveClass('counter');

// If we integrate jest-dom
const counter = $(<Counter />);
expect(counter.first()).toHaveClass('counter');
```

**Comment by abuuzayr** [comment]
Ah good catch. I think that while yes, those are plenty (18) of methods to implement but not worth +30KB of deps?

Otherwise if there were a "thin" version/alternative of `jest-dom` exposing just the APIs that would be perfect.

**Comment by franciscop** [comment]
The very good news is that if we integrate/standardize around jQuery syntax, then we could try to find/use a jest-jquery or similar (there might be some).

**Comment by franciscop** [comment]
I would like to circle back on that, seeing the current methods from `jest-dom` I don't think it's a good idea to include them all indiscriminately. Some of them are massively more important than others, e.g. `toHaveClass`, `toHaveAttribute`, `toHaveStyle`, etc. seem very important while `.toBeRequired`, `toBeEnabled`, etc. seem totally unimportant.

PS, I've [improved the homepage](https://react-test.dev/) quite a bit.

**Comment by abuuzayr** [comment]
@franciscop nice! I saw the 8 jest matches you chose to add and I'll have to agree. I think it is a good balance between what they have and what we need, and keeping to the light size of this library. I'm adding the remaining matches as issues and then I think this issue can be closed?

**Comment by abuuzayr** [comment]
Done!

- [Add API for jest matcher .toBeEnabled()](https://github.com/franciscop/react-test/issues/17)
- [Add API for jest matcher .toHaveAttribute()](https://github.com/franciscop/react-test/issues/18)
- [Add API for jest matcher .toHaveHtml()](https://github.com/franciscop/react-test/issues/19)
- [Add API for jest matcher .toHaveStyle()](https://github.com/franciscop/react-test/issues/20)
- [Add API for jest matcher .toHaveText()](https://github.com/franciscop/react-test/issues/21)
- [Add API for jest matcher .toHaveValue()](https://github.com/franciscop/react-test/issues/22)
- [Add API for jest matcher .toMatchSelector()](https://github.com/franciscop/react-test/issues/23)

**Comment by franciscop** [comment]
Thanks! Yes, that's perfect. I'll add some more info, write a blog post and start sharing it around to see if I can find people who want to contribute :)
