### ISSUE TITLE
Add API for jest matcher .toBeEnabled()

### ISSUE THREAD

**Issue by abuuzayr** [franciscop/react-test#17]
Hi 👋 , this is an issue for those who want to start contributing to Open Source. Please make sure to [read the Contributing.md guide](https://github.com/franciscop/react-test/blob/master/Contributing.md) to install this library for dev. Then you can solve this issue, ask questions around and submit a Pull Request when you are ready! We'll review it and give tips.

***

This is a custom matcher for jest to check whether an element is not disabled for the user.

### Acceptance criteria

- [ ] `.toBeEnabled()` should be available
- [ ] includes tests for this API

### References

- [`jest-dom`'s `toBeEnabled`](https://github.com/testing-library/jest-dom#tobeenabled).
- The current [`toHaveClass`](https://github.com/franciscop/react-test/tree/master/src/jest-matchers/toHaveClass) as an example.

**Comment by franciscop** [comment]
Closed since it was already merged.
