### ISSUE TITLE
Add API for jest matcher .toHaveAttribute()

### ISSUE THREAD

**Issue by abuuzayr** [franciscop/react-test#18]
Hi 👋 , this is an issue for those who want to start contributing to Open Source. Please make sure to [read the Contributing.md guide](https://github.com/franciscop/react-test/blob/master/Contributing.md) to install this library for dev. Then you can solve this issue, ask questions around and submit a Pull Request when you are ready! We'll review it and give tips.

***

This is a custom matcher for jest to check whether all the elements have an attribute:

```js
const $link = $(<a href="#home">);
expect($link).toHaveAttribute('href', '#home');
```

### Acceptance criteria

- [ ] `.toHaveAttribute()` should be available
- [ ] includes tests for this API

### References

- [`jest-dom`'s `toHaveAttribute`](https://github.com/testing-library/jest-dom#toHaveAttribute)
- This library's [implementation of `.toHaveClass()`](https://github.com/franciscop/react-test/tree/master/src/jest-matchers/toHaveClass)

**Comment by akpark** [comment]
hi, I tried taking this on -- referenced here #29

**Comment by franciscop** [comment]
Looks great, thanks!
