### ISSUE TITLE
Add API for jest matcher .toHaveStyle()

### ISSUE THREAD

**Issue by abuuzayr** [franciscop/react-test#20]
Hi 👋 , this is an issue for those who want to start contributing to Open Source. Please make sure to [read the Contributing.md guide](https://github.com/franciscop/react-test/blob/master/Contributing.md) to install this library for dev. Then you can solve this issue, ask questions around and submit a Pull Request when you are ready! We'll review it and give tips.

***

This is a custom matcher for jest to check whether an element has css properties with the required values. It should only match if the element matches ALL the required properties:

```js
const Button = styled.button`
  background: red;
`;
const $button = $(<Button>Hello</Button>);
expect($button).toHaveStyle('background', 'red');
```

### Acceptance criteria

- [ ] `.toHaveStyle()` should be available
- [ ] includes tests for this API

### References

- [`jest-dom`'s `toHaveStyle`](https://github.com/testing-library/jest-dom#toHaveStyle)
- The current [implementation of `.toHaveClass()`](https://github.com/franciscop/react-test/tree/master/src/jest-matchers/toHaveClass) as an example.
- [Mozilla Developer Network's `getComputedStyle`](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle)

**Comment by SheaMurphy** [comment]
Hi guys. I'd like to work on this if that's okay?

**Comment by abuuzayr** [comment]
of course @SheaMurphy! please do and let us know if you come across any issues.

**Comment by franciscop** [comment]
This is likely the most complex one of the jest matchers so feel free to ask questions! The idea is to be able to do:

```js
expect($button).toHaveStyle("border", "1px solid blue");
expect($button).toHaveStyle({ background: "red", fontSize: "16px" });   // camelCase or snake-case?
```

**Comment by SheaMurphy** [comment]
Yeah there's definitely some layers to it but I've made some good progress so far with functionality and corresponding tests. Just working on getting the correct error output in certain edge cases.

Currently have it working with styles argument of either type string or type object however I have used a single string input as that is the implementation in the jest-dom docs you've listed above.

```
expect($button).toHaveStyle("border: 1px solid blue"); // Intended usage of the method as it stands
expect($button).toHaveStyle("border: 1px solid blue; display: none"); // Intended usage with string argument including multiple styles
```
Would be good to get feedback on this before I do anymore in that area.

**Comment by SheaMurphy** [comment]
@franciscop Was the above implementation okay?

Also I'm having a little trouble testing that the method works when trying to find styles applied through a css class rather than inline as Jest falls over when linking the index.js to a stylesheet. I'm confident the way I've implemented the method will work but obviously want to test this. Any suggestions?

**Comment by franciscop** [comment]
I am not sure how the style is being calculated so not sure about the CSS class. If possible that'd be ideal, otherwise depending on the implementation it might be okay to skip it. Are you using [`getComputedStyle()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle) for this?

**Comment by SheaMurphy** [comment]
I'm not as I couldn't run the tests without a window object to call get computed style. I've tested it against a number of conditions and it seems reliable. If I set up a PR you'll be able to see how I've implemented it and then we can decide whether to push ahead or go back and work through a different implementation.

**Comment by SheaMurphy** [comment]
@franciscop @abuuzayr There's a PR in for this currently but wasn't able to add a reviewer so have tagged you both here in the hope you get a notification

**Comment by abuuzayr** [comment]
@SheaMurphy thanks for this PR, I'm so sorry i haven’t been able to take a look!

I will have a look tonight, on a brief look it looks awesome, thank you for putting so much time and effort

**Comment by SheaMurphy** [comment]
@abuuzayr no problem! I was just worried the notifications wern't coming through on the PR. Thanks for the initial feedback though. Just let me know if anything needs tweaking or updating
