### ISSUE TITLE
Add API for jest matcher .toHaveValue()

### ISSUE THREAD

**Issue by abuuzayr** [franciscop/react-test#22]
Hi 👋 , this is an issue for those who want to start contributing to Open Source. Please make sure to [read the Contributing.md guide](https://github.com/franciscop/react-test/blob/master/Contributing.md) to install this library for dev. Then you can solve this issue, ask questions around and submit a Pull Request when you are ready! We'll review it and give tips.

***

This is a custom matcher for jest to check whether a form element contains a specific value:

```js
const $input = $(<input value="bye" />);
await $input.type("Hello world");
expect($input).toHaveValue("Hello world");
```

> ~Note: this depends on `.type()`, which is not ready yet.~

### Acceptance criteria

- [ ] `.toHaveValue()` should be available
- [ ] includes tests for this API

### References

- [`jest-dom`'s `.toHaveValue()`](https://github.com/testing-library/jest-dom#toHaveValue)
- The current [implementation of `.toHaveClass()`](https://github.com/franciscop/react-test/tree/master/src/jest-matchers/toHaveClass) as an example.

**Comment by dreewp** [comment]
I can also work on this if you don't mind?

**Comment by franciscop** [comment]
No problem! Approved, thanks!
