### ISSUE TITLE
Add API for jest matcher .toMatchSelector()

### ISSUE THREAD

**Issue by abuuzayr** [franciscop/react-test#23]
Hi 👋 , this is an issue for those who want to start contributing to Open Source. Please make sure to [read the Contributing.md guide](https://github.com/franciscop/react-test/blob/master/Contributing.md) to install this library for dev. Then you can solve this issue, ask questions around and submit a Pull Request when you are ready! We'll review it and give tips.

***

This is a custom matcher for jest to check whether the elements match the DOM's query selector:

```js
const $button = $(<button className="primary">Click</button>);
expect($button).toMatchSelector("button.primary");
```

### Acceptance criteria

- [ ] `.toMatchSelector()` should be available
- [ ] includes tests for this API
- [ ] has some description and examples

### References

- The current [implementation of `.toHaveClass()`](https://github.com/franciscop/react-test/tree/master/src/jest-matchers/toHaveClass) as an example.

**Comment by franciscop** [comment]
@abuuzayr it seems clear that this has not worked as well as expected 🤷‍♂

When I did it with Umbrella JS, it was only few days from creating a new beginner-friendly issue until someone made a PR. I am not sure what is different, but if things do not change I'm going to go ahead and create the functionality in these issues over the weekend, please feel free to do so if you want (or no), thanks for all the help so far!

**Comment by abuuzayr** [comment]
No worries @franciscop ! This was a good experience overall for me. Do leave some issues for me! 

Perhaps it's that testing libraries are not as exciting as DOM manipulation libraries? Small app makes probably don't do testing as much as they do DOM manipulation. 

Also, while Umbrella was framework agnostic, this library is restricted to React users. Thats probably a much smaller subset.. 

In any case, thank you for creating this library! You have one supporter nonetheless. :)

**Comment by akpark** [comment]
gave this one a shot as well, link -- #30

**Comment by franciscop** [comment]
Thanks! There seems to be a formatting typo as noted there, otherwise approved!
