### ISSUE TITLE
Add API for .closest()

### ISSUE THREAD

**Issue by abuuzayr** [franciscop/react-test#3]
Acceptance criteria
-------------------

- [x] API for testing with `.closest()` method - [Umbrella's `.closest()`](https://umbrellajs.com/documentation#closest)
- [x] Tests for `.closest()`
- [ ] ~~Updated `index.min.js`~~

**Comment by abuuzayr** [comment]
@franciscop will committing `index.min.js` be required? I remember you saying that you generate it when releasing a new version.. Otherwise we can also set up a GitHub action to auto generate it and add a commit on a PR to master.

**Comment by franciscop** [comment]
Hey @abuuzayr, committing `index.min.js` would not make a big difference since the publishing script I use will rebuild it anyway. I think it's better to avoid it, since it'll add noise to the PR. Just published `v0.3.0` 🎉

**Comment by abuuzayr** [comment]
Roger that @franciscop, added a PR for this API too!

**Comment by franciscop** [comment]
Thanks for adding all of the Issues! Let me see if I can put together a Contributing.md and publish this in https://up-for-grabs.net/ and Reddit so other people can also contribute 😄
