### ISSUE TITLE
Add API for .data()

### ISSUE THREAD

**Issue by abuuzayr** [franciscop/react-test#5]
Hi 👋 , this is an issue for those who want to start contributing to Open Source. Please make sure to [read the Contributing.md guide](https://github.com/franciscop/react-test/blob/master/Contributing.md) to install this library for dev. Then you can solve this issue, ask questions around and submit a Pull Request when you are ready! We'll review it and give tips.

***

Create a method that reads the specified [data attribute](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) of the first matched element:

```js
const $div = $(<div data-abc="def">hello</div>);
console.log($div.data("abc"));
// def
```

### Acceptance criteria

- [x] API for testing with `.data()` method
- [x] Basic tests for `.data()`

### Nice to have but not required

- [x] Documentation
- [ ] Tests for edge cases

### References

- [React Test's `.find()`](https://github.com/franciscop/react-test/tree/master/src/methods/find) as an example of a well-defined method.
- [Umbrella's `.data()`](https://umbrellajs.com/documentation#data) as an example of documentation for a similar method.
- [jQuery's `.data()`](https://api.jquery.com/data/) the original one.
- [Mozilla Developer Network's documentation](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes).

**Comment by EGimenoS** [comment]
Hi!

First of all, thank you for this initiative, IT is a fantastic opportunity to get started.

I have been working on this issue and I already have an implementation of the method plus a couple of tests and some documentation. I would like to make a PR but I don't know exactly which workflow should I follow. 

As suggested in your contributing docs I cloned the repo. I have locally made a branch for the feature, but now, how should I make the PR? Should I fork the repo?

Thank you!

**Comment by EGimenoS** [comment]
Nevermind, I think I figured it out.

Since I had cloned the repo before forking it, I have used this strategy:
[https://gist.github.com/jagregory/710671](url)

Also for beginners, this step-by-step tutorial might me good to learn the basic workflow to contribute:
[https://codeburst.io/a-step-by-step-guide-to-making-your-first-github-contribution-5302260a2940](url)

**Comment by franciscop** [comment]
That is a great point, thanks! Just improved the `Contributing.md` guide to add the tutorial and removed the point where it said to clone it first.

**Comment by franciscop** [comment]
Fixed in https://github.com/franciscop/react-test/pull/25 🎉
