### ISSUE TITLE
Add API for .each()

### ISSUE THREAD

**Issue by abuuzayr** [franciscop/react-test#6]
Hi 👋 , this is an issue for those who want to start contributing to Open Source. Please make sure to [read the Contributing.md guide](https://github.com/franciscop/react-test/blob/master/Contributing.md) to install this library for dev. Then you can solve this issue, ask questions around and submit a Pull Request when you are ready! We'll review it and give tips.

***

### Acceptance criteria

- [ ] API for testing with `.each()` method - [Umbrella's `.each()`](https://umbrellajs.com/documentation#each)
- [ ] Tests for `.each()`

### Nice to have but not required

- [ ] Documentation
- [ ] Tests for edge cases

### References

- [React Test's `.find()`](https://github.com/franciscop/react-test/tree/master/src/methods/find) as an example of a well-defined method.
- [Umbrella's `.each()`](https://umbrellajs.com/documentation#each) as an example of documentation for a similar method.
- [jQuery's `.each()`](https://api.jquery.com/each/) the original one.

**Comment by franciscop** [comment]
I'm temporarily closing this until I get a better understanding on https://github.com/franciscop/react-test/issues/32
