### ISSUE TITLE
Add API for .filter() 

### ISSUE THREAD

**Issue by abuuzayr** [franciscop/react-test#7]
Hi 👋 , this is an issue for those who want to start contributing to Open Source. Please make sure to [read the Contributing.md guide](https://github.com/franciscop/react-test/blob/master/Contributing.md) to install this library for dev. Then you can solve this issue, ask questions around and submit a Pull Request when you are ready! We'll review it and give tips.

***

Keep only the nodes that match the passed selector:

```js
// Only <a class="button"> and not others like <label class="button">
$(<Page />).find(".button").filter("a");
```

### Acceptance criteria

- [ ] API for testing with `.filter()` method
- [ ] Basic tests for `.filter()`

### Nice to have but not required

- [ ] Documentation
- [ ] Tests for edge cases

### References

- [React Test's `.find()`](https://github.com/franciscop/react-test/tree/master/src/methods/find) as an example of a well-defined method.
- [Umbrella's `.filter()`](https://umbrellajs.com/documentation#filter) as an example of documentation for a similar method.
- [jQuery's `.filter()`](https://api.jquery.com/filter/) the original one.
- [Mozilla Developer Network's `.filter()` documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter).

**Comment by franciscop** [comment]
I'm temporarily closing this until I get a better understanding on https://github.com/franciscop/react-test/issues/32
