### ISSUE TITLE
Add API for .parent()

### ISSUE THREAD

**Issue by abuuzayr** [franciscop/react-test#9]
Hi 👋 , this is an issue for those who want to start contributing to Open Source. Please make sure to [read the Contributing.md guide](https://github.com/franciscop/react-test/blob/master/Contributing.md) to install this library for dev. Then you can solve this issue, ask questions around and submit a Pull Request when you are ready! We'll review it and give tips.

***

### Acceptance criteria

- [ ] API for testing with `.parent()` method - [Umbrella's `.parent()`](https://umbrellajs.com/documentation#parent)
- [ ] Basic tests for `.parent()`

### Nice to have but not required

- [ ] Documentation
- [ ] Tests for edge cases

### References

- [React Test's `.find()`](https://github.com/franciscop/react-test/tree/master/src/methods/find) as an example of a well-defined method.
- [Umbrella's `.parent()`](https://umbrellajs.com/documentation#parent) as an example of documentation for a similar method.
- [jQuery's `.parent()`](https://api.jquery.com/parent/) the original one.
- [Mozilla Developer Network's `.parentNode` documentation](https://developer.mozilla.org/en-US/docs/Web/API/Node/parentNode).

**Comment by vaske** [comment]
hi guys I would like to add this one, should I report myself anywhere or just open a PR?

**Comment by franciscop** [comment]
Just a PR was great, thanks!
